### ISSUE TITLE
tutorial please

### ISSUE THREAD

**Issue by iamdenzen** [shobhitsharma/embedo#10]
sir, i'm having problem in using embedo for my project... because i'm a bit confused about how to use it... so it would be really helpful for me if you tell me how and where to define the facebook or any other link to get the results shown on the site... i will be waiting for you to respond... thanks

**Comment by shobhitsharma** [comment]
@iamdenzen FB now has some security issue in sandbox rending or codepen/jsfiddle, but this link should work fine for development http://jsfiddle.net/shobhit_sharma/7fnrzmj9/
