### ISSUE TITLE
Instagram CORB 

### ISSUE THREAD

**Issue by Pavel910** [shobhitsharma/embedo#13]
Hi, I'm trying to implement this library, but ran into problems with Instagram.
Instagram example also does not work on your Codepen, so I was wondering if there is a way to get around this:

![image](https://user-images.githubusercontent.com/3920893/47869021-18ad9800-de06-11e8-9ac4-fbd6f5695e55.png)

Thanks!

**Comment by shobhitsharma** [comment]
@Pavel910 Thanks for reporting this issue. I've patched it in newest version. Please upgrade and test again.
