### ISSUE TITLE
how to replace the default css?

### ISSUE THREAD

**Issue by youyi1314** [shobhitsharma/embedo#17]
As title,
when i render it out, there are a default css there, it will run out of div.
`<div id="embedo_arc5ry" data-embedo-id="embedo_arc5ry" data-embedo-source="facebook" style="display: flex; text-align: center; justify-content: center; align-items: center; margin: 0px auto; width: 750px; height: 500px;"><div class="fb-page fb_iframe_widget" data-href="https://www.facebook.com/facebook/" data-width="750" data-height="500" fb-xfbml-state="rendered" fb-iframe-plugin-query="app_id=1757323867855573&amp;container_width=308&amp;height=500&amp;href=https%3A%2F%2Fwww.facebook.com%2Ffacebook%2F&amp;locale=en_US&amp;sdk=joey&amp;width=750"><span style="vertical-align: bottom; width: 308px; height: 214px;"><iframe name="f3a93801707721c" width="750px" height="500px" frameborder="0" allowtransparency="true" allowfullscreen="true" scrolling="no" allow="encrypted-media" title="fb:page Facebook Social Plugin" src="https://www.facebook.com/plugins/page.php?app_id=1757323867855573&amp;channel=https%3A%2F%2Fstaticxx.facebook.com%2Fconnect%2Fxd_arbiter.php%3Fversion%3D44%23cb%3Df2dee353410122%26domain%3Dlocalhost%26origin%3Dhttp%253A%252F%252Flocalhost%253A3000%252Ff344933bfc48d6c%26relation%3Dparent.parent&amp;container_width=308&amp;height=500&amp;href=https%3A%2F%2Fwww.facebook.com%2Ffacebook%2F&amp;locale=en_US&amp;sdk=joey&amp;width=750" style="border: none; visibility: visible; width: 308px; height: 214px;" class=""></iframe></span></div></div>`
As html it render can see that element id : **embedo_arc5ry**
has css `display: flex; text-align: center; justify-content: center; align-items: center; margin: 0px auto; width: 750px; height: 500px;`
how can i change it?

**Comment by shobhitsharma** [comment]
You can disable it using following options as [mentioned in docs here](https://github.com/shobhitsharma/embedo/wiki/Options#native-options)
```js
{
  ...
  centerize: false,
  strict: true
}
```
Let me know if that helps!
