### ISSUE TITLE
adding new providers? (sproutvideo)

### ISSUE THREAD

**Issue by meecect** [shobhitsharma/embedo#18]
How would I go about adding a new provider?

In particular I was interested in adding support for SproutVideo.  Here is an example of how embedly does it:

https://embed.ly/code?url=https%3A%2F%2Fcooking-show.vids.io%2Fvideos%2Fa49ddeb31a1be4c42c%2Fclassic-cooking-lessons-hosting-a-dinner-party

**Comment by shobhitsharma** [comment]
@meecect As I read from [SproutVideo embed docs](https://sproutvideo.com/help/articles/16-how_to_embed_a_video), they just give simple URL to embed, which should work out-of-box if you use it as described using fallback `iframe` renderer of embedo.

Try to paste: 
```
https:////videos.sproutvideo.com/embed/709adcb31f19e5c6f8/cd8cf2e796aa69d3
```
into [embedo's demo page](https://shobhitsharma.github.io/embedo/) and see result.
