### ISSUE TITLE
Twitter Embed doesn't work

### ISSUE THREAD

**Issue by teddy-dev** [shobhitsharma/embedo#21]
It seems that twitter embed doesn't work. It happens on https://shobhitsharma.github.io/embedo/ to.

**Comment by shobhitsharma** [comment]
Works fine in my tests. What URL you tried?
<img width="828" alt="Screenshot 2019-12-06 at 13 18 49" src="https://user-images.githubusercontent.com/772855/70322647-f6692380-182a-11ea-8e42-5856010a6696.png">

**Comment by teddy-dev** [comment]
I'm sorry. The problem happened because i was using Brave browser with Brave Shield Activated

Here is the picture when Brave shield was disabled
![0](https://user-images.githubusercontent.com/56222671/70328641-1cfb7e80-186c-11ea-9643-e0b64611f026.png)

Here is the picture when i was using Brave Shiled
![2](https://user-images.githubusercontent.com/56222671/70328698-3dc3d400-186c-11ea-8926-660f93c8795c.png)
![1](https://user-images.githubusercontent.com/56222671/70328703-41575b00-186c-11ea-997e-4ee660162091.png)

But for Instragram content with brave Shield enabled, it works
![3](https://user-images.githubusercontent.com/56222671/70328762-6350dd80-186c-11ea-8b63-e517f6497834.png)
