### ISSUE TITLE
CodePen embedo - React Component isn't ok

### ISSUE THREAD

**Issue by hypervalley** [shobhitsharma/embedo#22]
This package is fantastic. It's what I was looking for. 

Please, correct the usage link "Codepen - Using with React" (https://codepen.io/shobhitsharma/pen/prOGzd). It shows a blue screen. 

The other link, https://codepen.io/shobhitsharma/pen/yojJZp, is ok.

Regards.

**Comment by shobhitsharma** [comment]
Works now. Closing.
