### ISSUE TITLE
Youtube allow fullscreen

### ISSUE THREAD

**Issue by lineke** [shobhitsharma/embedo#28]
Is it possible to enable the fullscreen button in youtube embedded video's? Since it does not seem to be possible according to the code, if I read it correctly.

**Comment by shobhitsharma** [comment]
@lineke Moin Moin. You can pass options  as arguments in `.load()` function, see example here. It supports anything that youtube supports.

```js
  embedo.load(
    document.getElementById('test-container'),
    'https://www.youtube.com/watch?v=RLWcYADoV84',
    { allowfullscreen: true, autoplay: true }
  );
```

https://codepen.io/shobhitsharma/pen/gOLOYWP
