### ISSUE TITLE
Support for oembed discovery?

### ISSUE THREAD

**Issue by mindplay-dk** [shobhitsharma/embedo#9]
It appears there's no support for oembed discovery?

For example, flickr URLs do not appear to be supported - although flickr provides `<link rel="alternative">` tags on their pages with oembed (in JSON and XML formats) discoverable.

Is this "by design"?

**Comment by shobhitsharma** [comment]
@mindplay-dk Yes, Flickr allows oembed extraction via json/xml from their oembed API ([see this example](https://www.flickr.com/services/oembed?url=https://flic.kr/p/hsd5so&format=json))

```
https://www.flickr.com/services/oembed?url=[PHOTO_URL_HERE]&format=json
```

OR, alternatively its also possible to generate embed component if I hook in their SDK to embedo base class.

```
https://embedr.flickr.com/assets/client-code.js
```

I'll add support over the weekend, and possibly write a function so plugins can be created using existing embedo internals.

**Comment by mindplay-dk** [comment]
Meanwhile, I think we're now leaning towards server-side embed expansions, for performance reasons - to avoid the extra HTTP hit on the client-side. Not sure yet. If we do decide on client-side embed expansion, this does look like a nice library :-)

**Comment by shobhitsharma** [comment]
Yes, I wrote this library to solve our problem of embedding public content (with many hits) without any hooks to our backend. But there are pricing based services like iframely or embedly which does that.

**Comment by shobhitsharma** [comment]
https://github.com/shobhitsharma/embedo/issues/24
